version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: sentinel-redis
    restart: always
    # No ports exposed to host for security, only internal network
    expose:
      - "6379"

  shield:
    build: ./Shield-Proxy
    container_name: sentinel-shield
    restart: always
    depends_on:
      - redis
    ports:
      - "80:8081" # Change the first 80 to whatever public port you want
    environment:
      - SHIELD_PORT=8081
      - BACKEND_URL=http://host.docker.internal:4000 # Point this to your actual app
      - USE_REDIS=true
      - REDIS_URL=redis://redis:6379
      - ADMIN_KEY=1234
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows Shield to talk to apps on the host machine
